baseurl: "https://lyohe.github.io"
languageCode: "ja-jp"
title: "ã“ã“ã«ã‹ã"
theme: "hugo-tania"

params:
  titleEmoji: 'ğŸ¦¥'

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true
