baseurl: "https://lyohe.github.io"
languageCode: "ja-jp"
title: "ã“ã“ã«ã‹ã"
author: "Ryohei Tsuda"
theme: "hugo-tania"

params:
  title: "ã“ã“ã«ã‹ã"
  titleEmoji: 'ğŸ¦¥'
  description: "ä¼šè¨ˆã¨ãƒ—ãƒ­ã‚°ãƒ©ãƒŸãƒ³ã‚°"
  images:
  - tori.JPG

menu:
  header:
    - name: twitter
      url: "https://twitter.com/rtsudar"
    - name: medium
      url: "https://lyohe.medium.com/"
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true
